### ISSUE TITLE
Proper way to load pretrained weights as a model

### ISSUE THREAD

**Issue by ncdejito** [speed8928/IMELE#1]
Is there a proper way to load the Gdrive file as a model? I've been getting an ordered_dict when I load it, and the code asks for (1) an Encoder, (2) num_features, (3) block_channel.

```
import torch
pretrained_weights = torch.load('Block0_skip_model_110.pth.tar')
pretrained_weights['state_dict'].keys()
```

**Comment by speed8928** [comment]
I have updated the repository. I think you may reference to trained.py to see how to load the model.
