### ISSUE TITLE
Missing 'test_rgb_base/' directory in Google Drive

### ISSUE THREAD

**Issue by p-geon** [speed8928/IMELE#10]
Thanks for the great work! These results are very attractive!

To check the pre-trained model, I tried to run a test model.
But I cannot find RGB test data.

![スクリーンショット 2021-06-11 21 11 58](https://user-images.githubusercontent.com/30303550/121684472-b22ea180-caf9-11eb-8105-921eb20a73b9.png)

↑This is my view of Google Drive.

**Comment by speed8928** [comment]
Hey I just update the testing rgb, you shall see it now,

**Comment by p-geon** [comment]
Thank you for your prompt response! 👍
