### ISSUE TITLE
RuntimeError: shape '[-1, 250, 250]' is invalid for input of size 6195200

### ISSUE THREAD

**Issue by ykzou9** [speed8928/IMELE#16]
Hello, when I was using the model and data you provided for training, I encountered the following error: RuntimeError: shape '[-1, 250, 250]' is invalid for input of size 6195200. I'm not sure how this error occurred. I would greatly appreciate it if you could provide some guidance.
![error](https://github.com/speed8928/IMELE/assets/125784131/571c0982-bb33-4b25-a5a5-bf6920799ce4)

**Comment by Arham222** [comment]
Somehow I have faced the same error but I think it is for the image output size and I have seeing some changes in original data as data provided is change and its ground truth dsm also updated so I comment that line and resolve that issue you can try that same

**Comment by ykzou9** [comment]
> 不知何故，我遇到了同样的错误，但我认为这是针对图像输出大小的，我看到原始数据发生了一些变化，因为提供的数据发生了变化，并且其基本事实 dsm 也更新了，所以我评论该行并解决了该问题，您可以尝试相同的操作

Your advice is very effective. Thank you very much.

**Comment by ykzou9** [comment]
> Somehow I have faced the same error but I think it is for the image output size and I have seeing some changes in original data as data provided is change and its ground truth dsm also updated so I comment that line and resolve that issue you can try that same

I want to ask if you have encountered such a problem. I reported the following error when running the test.py file: 
![error2](https://github.com/speed8928/IMELE/assets/125784131/461e38ad-2415-4aee-b99f-eb6fe78286de)

**Comment by Arham222** [comment]
Did you train it on resnet or senet?

**Comment by ykzou9** [comment]
> 

Yes, I've trained on SENet, but when I tried testing, I encountered this error.

**Comment by Arham222** [comment]
Then I think your model is not trained properly because it misses some weights you should try to retrain your model with senet 161

**Comment by ykzou9** [comment]
> Then I think your model is not trained properly because it misses some weights you should try to retrain your model with senet 161

Sure, I'll give it another shot following your advice. Thanks for taking the time to help despite your busy schedule. If I have more questions, I might need to ask you again.

**Comment by ykzou9** [comment]
> Then I think your model is not trained properly because it misses some weights you should try to retrain your model with senet 161

Hello, I'm back with another question. After retraining as per your advice, I encountered the following issue: AttributeError: 'function' object has no attribute 'SSIM'. I couldn't resolve it. Can you provide some insights? Thanks!
![error3](https://github.com/speed8928/IMELE/assets/125784131/2eaf77a7-e6c8-4b47-8250-30c951d5c4b2)
This is the link to my relevant code: [GitHub Link](https://github.com/ykzou9/IMELE_Copy/blob/master/test.py).

**Comment by Arham222** [comment]
ssim is depreciated it doesnot work with the latest python anymore I suggest you to not use structural similarity error matrix or if it is important then you have to use virtual env for specific python version and respective library in which ssim is compatible my advice is comment that error matrix use rmse mae and mse

**Comment by ykzou9** [comment]
> ssim is depreciated it doesnot work with the latest python anymore I suggest you to not use structural similarity error matrix or if it is important then you have to use virtual env for specific python version and respective library in which ssim is compatible my advice is comment that error matrix use rmse mae and mse

OK, I really appreciate it!

**Comment by ykzou9** [comment]
> ssim is depreciated it doesnot work with the latest python anymore I suggest you to not use structural similarity error matrix or if it is important then you have to use virtual env for specific python version and respective library in which ssim is compatible my advice is comment that error matrix use rmse mae and mse

During the testing phase, I encountered the following error when using the provided training files:
![error4](https://github.com/speed8928/IMELE/assets/125784131/f1180b2b-444c-4be7-acd9-9d8152dc7d63)

I noticed that someone had a similar issue before and proposed a solution：
![suggestion](https://github.com/speed8928/IMELE/assets/125784131/cf082d7e-32a3-4a2f-8d1b-1faf168eea53)

I tried, but then encountered the following problem:
![error5](https://github.com/speed8928/IMELE/assets/125784131/075ef276-ac74-48be-8b7d-a667e3288d9b)

I am currently deeply troubled by this issue and look forward to your guidance.
