### ISSUE TITLE
Request for Dublin city Data

### ISSUE THREAD

**Issue by shnhrtkyk** [speed8928/IMELE#2]
First, I just want to say THANK YOU for this good work.
I would like to do a reproduction experiment and a performance comparison, so would you publish the data used in the experiment in the paper?
Best regards.

**Comment by speed8928** [comment]
Hey 

please find the link below to download the dataset.

https://drive.google.com/drive/folders/14sBkjeYY7R1S9NzWI5fGLX8XTuc8puHy?usp=sharing

**Comment by shnhrtkyk** [comment]
Thank you very much!
