### ISSUE TITLE
Proper way to run train.py file

### ISSUE THREAD

**Issue by shivshaktiss17** [speed8928/IMELE#6]
Hello,
I am a newbie in the field of CNN and Height estimation (currently working on my skills).
I have seen your code, great efforts.

Please help to properly run the file, so that I can get output and understand it.
Thank you.

I have downloaded all the required files, but don't have the proper idea of running the command.

Do I have to pass anything else in the **command-line argument**? like training file path or...anything?
**Any specific file for CSV heights**? Regarding **depth_name** and **depth**. It is creating some problem in **loading.py** file.
As I have tried all CSV, not any of them contains height information. If I am wrong, please enlighten me.
Thank you again.

**Comment by speed8928** [comment]
Hi you should look at the argpaser in the train.py and you would know what to pass. If there is error in loading data you could debug it in dataloader. I do not quite sure what is your problem, so I am going to close the comment.
